### ISSUE TITLE
Execute commands in a nested process 

### ISSUE THREAD

**Issue by matrixise** [sloria/doitlive#25]
Thank you for your job, the project is awesome and useful.
but I wanted to execute some commands to `pdb` and use asciinema and replay the scenario with your tool and asciinema.

There are the python and ipython modes, but how do you think I can work  with `python -m pdb myscript.py` ? because in the code, you check (with regex) if you will select `python` or `ipython` mode.

Again, how will you handle the case where you can show a debugging session with gdb ?

Here is a small example with `pdb`

```
python -m pdb script.py
break
break main
continue
quit
```

Have you an idea?

Have a nice day and thank you.

**Comment by sloria** [comment]
The `python` and `ipython` commands are special cases. They start custom `InteractiveConsole` and `TerminalIPythonApp` classes, respectively. `pdb` support would be tricky; I'm not sure how doitlive would hook into the input for it. `gdb` is probably not going to happen either, since it's not Python code.
