### ISSUE TITLE
support setting variables in a script

### ISSUE THREAD

**Issue by asmacdo** [sloria/doitlive#32]
Variables cannot be set within a live script:

`$ cat variables.sh`

    export SET_VAR="Please add support for variables"
    echo $SET_VAR

`$ doitlive play variables.sh`        
```                                                                                                                                                         
We'll do it live!
STARTING SESSION: Press Ctrl-C at any time to exit.
Press any key to continue ...
```
```
austin@dhcp129-212.rdu.redhat.com:devel $ export SET_VAR="Please add support for variables"
austin@dhcp129-212.rdu.redhat.com:devel $ echo $SET_VAR

austin@dhcp129-212.rdu.redhat.com:devel $ 
FINISHED SESSION
```

Just as a sanity check...
`bash variables.sh`

    Please add support for variables

**Comment by sloria** [comment]
@asmacdo  You can use `#doitlive env: <VAR>=<value>` as a workaround.

```bash
export NAME=Austin
#doitlive env: NAME=Austin
echo 'Hello' $NAME
```

Each command run in a session executes in its own environment, so `export` commands don't persist envvars to the next command. Use the above workaround for now. 

Maybe doitlive should parse out `export` commands and save those variables automatically...

**Comment by sloria** [comment]
If I get some time this weekend, I'll see if I can make so that `export` commands work as expected. If you need it sooner, I'd definitely review/merge a PR. I think it's a matter of adding some logic here:

https://github.com/sloria/doitlive/blob/bcf2bff9cec798575efca4d93c1d6ec69c1cf351/doitlive/__init__.py#L570

Might be as simple as adding an `elif command.startswith('export')` and then calling `state.add_envvar(command.split()[1])`.
