### ISSUE TITLE
Some keystrokes escape and get echoed

### ISSUE THREAD

**Issue by jordigh** [sloria/doitlive#6]
I am working on Debian GNU/Linux, and I'm having trouble with some keystrokes getting echoed instead of getting swallowed. This is probably going to be difficult to debug, since it's obviously a timing problem, and I assume it must be dependent on something on my system.

I'll attempt to fix this myself, but I'm recording the problem here for posterity.

**Comment by ReAzem** [comment]
I am on Debian too and I get the same issue. A good percentage of the keystrokes get don't get swallowed actually.

**Comment by Stefan-Code** [comment]
Hi there,
I am also using having the same issue. Has a solution for this problem been found?

**Comment by Stefan-Code** [comment]
I created an issue over at [the click project] (https://github.com/mitsuhiko/click/issues/435) as it's really a click issue.

**Comment by untitaker** [comment]
See my response there, as a fix for this I would recommend not relying on `getchar` anymore, because the bugfix in click means breaking API compat. Instead, set the termmode outside of the loop you probably have.

In the future click probably should provide a more convenient (and cross-platform) API (e.g. a context mgr) for `tty.setraw`, but right now it doesn't.

**Comment by Stefan-Code** [comment]
Thanks! Just setting the raw mode outside of the loop seems like an easy fix for this issue.

**Comment by Stefan-Code** [comment]
I fixed this issue [in my fork](https://github.com/Stefan-Code/doitlive) for Python 3 and 2 (although I can't seem to get the unit-tests to work for python2). @sloria Pull requests welcome?

**Comment by sloria** [comment]
Pull requests are certainly welcome. Thank you for working on this issue.

I am also unable to test against Windows, so I haven't decided on whether to support it. Could you make it so that your fix only applies to non-Windows systems?

**Comment by Stefan-Code** [comment]
Also in windows fixing this (if it is a problem at all, which probably depends on how fast msvcrt.getch() is) would be a bit trickier. ~~because I'm not aware of any raw mode for the windows command line that could be set.~~ It seems like there is [some kind of equivalent] (https://msdn.microsoft.com/en-us/library/ms683167(VS.85).aspx). I will adjust my fix to not apply for windows for now.
