### ISSUE TITLE
doitlive handling of shell meta-metacharacters

### ISSUE THREAD

**Issue by jhajek** [sloria/doitlive#9]
Hi - love the product. I am a professor using it to teach Linux shell to a class of undergrads - makes demos so much smoother.   I have attached a session-test.sh file, I noticed that doitlive doesn't handle shell meta-characters, for instance ~- and the backtick example of DT=`date`; echo $DT will be blank.  Using Fedora 22 on Gnome-Terminal

What is your opinion?  

session.sh
```
cd ~/Documents
pwd
cd ~/Downloads
pwd
cd ~-
pwd
clear
DT=`date`
echo $DT
date
DT=date
echo $DT
DT=5
echo $DT
```

**Comment by sloria** [comment]
Thanks @jhajek for reporting. `doitilive` uses click's `echo` function for printing characters. I recommend that you report this issue there: https://github.com/mitsuhiko/click

**Comment by sloria** [comment]
Out of curiosity, what versions of Python and click are you using?

**Comment by sloria** [comment]
Ah, sorry I misunderstood the original issue. The problem lies in how doitlive runs each command. It writes the command to a temporary file then executes it. This is necessary for certain shell built-ins to work: https://github.com/sloria/doitlive/blob/784cba2ea028f85b14225af0b061f0aa90bfc9b3/doitlive.py#L308-L338

Since each command is written to a separate file, you can't use variables across commands. However, you can kind of fake it by using the `env` directive.

```python
#doitlive env: DT='Sun Oct  4 14:12:34 EDT 2015'
DT=`date`
echo $DT
```

Not sure how you'd fake `cd ~-`, though.

**Comment by jhajek** [comment]
I think that will work perfectly - I will use the environment variables to *fake* it - which is good enough for a class demo.  ```cd ~-``` is a bash-ism anyway. I could always use $OLDPWD and just create an environment variable like the example you showed.  Thanks for the help 
Python 2.7.10
Python 3.4.2
